function U_fiber_WMH_View(UFA_Output,view_choice)

% AUTHOR : Gaoxing Zheng
% Institution: Zhongshan Hospital, Fudan University
% EMAIL CONTACT: zheng_gao_xing@163.com
% DATE: 2022-04-14

if contains(view_choice,'whole_brain')
    
    unix(['mrview -load ',UFA_Output, '/WMH_extraction/subjects/Patient/mri/extractedWMH/Patient_WMH_FLAIRspace_coreg.nii.gz',' -imagevisible true -tractography.load ',UFA_Output,'/DWI/Tracking/*.tck -mode 2']);
    
elseif contains(view_choice,'U_fiber')
    
    unix(['mrview -load ',UFA_Output, '/WMH_extraction/subjects/Patient/mri/extractedWMH/Patient_WMH_FLAIRspace_coreg.nii.gz',' -imagevisible true -tractography.load ',UFA_Output,'/U_fibers/U_fibers.tck -mode 2']);
%     unix(['mrview -load ',UFA_Output, '/WMH_extraction/subjects/QC/QC_final_native/*.nii.gz',' -imagevisible true -tractography.load ',UFA_Output,'/WMA_clustering_SWM/U_fiber_tractography.tck -mode 2']);

%{

color_set = colormap;

Cindex = 1:16;

% Note that the option '-tractography.colour' is not provied in MRtrix3
% 3.0.2, you should update the latest MRtrix3 version. (Here I used verison 3.0.3)
% Linux shell command : conda update -c mrtrix3 mrtrix3

unix(['mrview -load ',UFA_Output, '/WMH_extraction/subjects/QC/QC_final_native/*.nii.gz',' -imagevisible true -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-F_left.tck -mode 2',' -tractography.opacity 1'...
    ,' -tractography.thickness 0 -tractography.colour ','"',num2str(color_set(Cindex(1),1)),',',num2str(color_set(Cindex(1),2)),',',num2str(color_set(Cindex(1),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-F_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(2),1)),',',num2str(color_set(Cindex(2),2)),',',num2str(color_set(Cindex(2),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-FP_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(3),1)),',',num2str(color_set(Cindex(3),2)),',',num2str(color_set(Cindex(3),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-FP_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(4),1)),',',num2str(color_set(Cindex(4),2)),',',num2str(color_set(Cindex(4),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-P_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(5),1)),',',num2str(color_set(Cindex(5),2)),',',num2str(color_set(Cindex(5),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-P_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(6),1)),',',num2str(color_set(Cindex(6),2)),',',num2str(color_set(Cindex(6),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PT_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(7),1)),',',num2str(color_set(Cindex(7),2)),',',num2str(color_set(Cindex(7),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PT_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(8),1)),',',num2str(color_set(Cindex(8),2)),',',num2str(color_set(Cindex(8),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-T_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(9),1)),',',num2str(color_set(Cindex(9),2)),',',num2str(color_set(Cindex(9),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-T_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(10),1)),',',num2str(color_set(Cindex(10),2)),',',num2str(color_set(Cindex(10),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-OT_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(11),1)),',',num2str(color_set(Cindex(11),2)),',',num2str(color_set(Cindex(11),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-OT_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(12),1)),',',num2str(color_set(Cindex(12),2)),',',num2str(color_set(Cindex(12),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PO_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(13),1)),',',num2str(color_set(Cindex(13),2)),',',num2str(color_set(Cindex(13),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PO_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(14),1)),',',num2str(color_set(Cindex(14),2)),',',num2str(color_set(Cindex(14),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-O_left.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(15),1)),',',num2str(color_set(Cindex(15),2)),',',num2str(color_set(Cindex(15),3)),'"'...
    ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-O_right.tck ',' -tractography.colour ','"',num2str(color_set(Cindex(16),1)),',',num2str(color_set(Cindex(16),2)),',',num2str(color_set(Cindex(16),3)),'"']); % -tractography.geometry pseudotubes  -tractography.colour "200,0,0"

%}

% unix(['mrview -load ',UFA_Output, '/WMH_extraction/subjects/QC/QC_final_native/*.nii.gz',' -imagevisible true -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-F_left.tck -mode 2',' -tractography.opacity 1'...
%     ,' -tractography.thickness 0'...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-F_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-FP_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-FP_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-P_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-P_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PT_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PT_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-T_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-T_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-OT_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-OT_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PO_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-PO_right.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-O_left.tck '...
%     ,' -tractography.load ',UFA_Output,'/WMA_clustering_SWM/T_Sup-O_right.tck ']); % -tractography.geometry pseudotubes  -tractography.colour "200,0,0"


end

end